# YAML -*- mode: yaml; tab-width: 2; indent-tabs-mode: nil; coding: utf-8 -*-
# SPDX-License-Identifier: BSD-3-Clause
# SPDX-FileCopyrightText: Z-Wave Alliance <https://z-wavealliance.org>
---
version: 2
updates:
  - package-ecosystem: gitsubmodule
    directory: /
    target-branch: main
    schedule:
      interval: weekly
    commit-message:
      prefix: 'chore(deps): '
