/// SPDX-License-Identifier: BSD-3-Clause
/// SPDX-FileCopyrightText: Silicon Laboratories Inc. https://www.silabs.com
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 
namespace ZWaveController.Configuration {
    using System;
    using System.ComponentModel;
    using System.Xml.Serialization;
    using System.Collections.ObjectModel;
    using ZWave.Configuration;
    
    
    [Serializable]
    [XmlTypeAttribute(AnonymousType=true)]
    [XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class ConfigurationItem {
        
        private PreKitting preKittingField;
        
        private ViewSettings viewSettingsField;
        
        private SecuritySettings securitySettingsField;
        
        private Collection<Node> nodeField;
        
        private string appVersionField;
        
        public PreKitting PreKitting {
            get {
                return this.preKittingField;
            }
            set {
                this.preKittingField = value;
            }
        }
        
        public ViewSettings ViewSettings {
            get {
                return this.viewSettingsField;
            }
            set {
                this.viewSettingsField = value;
            }
        }
        
        public SecuritySettings SecuritySettings {
            get {
                return this.securitySettingsField;
            }
            set {
                this.securitySettingsField = value;
            }
        }
        
        [XmlElementAttribute("Node")]
        public Collection<Node> Node {
            get {
                return this.nodeField;
            }
            set {
                this.nodeField = value;
            }
        }
        
        [XmlAttributeAttribute()]
        public string AppVersion {
            get {
                return this.appVersionField;
            }
            set {
                this.appVersionField = value;
            }
        }
    }
    
    [Serializable]
    public partial class ViewSettings {
        
        private IMAView iMAViewField;
        
        private SecurityView securityViewField;
        
        private EncryptDecryptView encryptDecryptViewField;
        
        public IMAView IMAView {
            get {
                return this.iMAViewField;
            }
            set {
                this.iMAViewField = value;
            }
        }
        
        public SecurityView SecurityView {
            get {
                return this.securityViewField;
            }
            set {
                this.securityViewField = value;
            }
        }
        
        public EncryptDecryptView EncryptDecryptView {
            get {
                return this.encryptDecryptViewField;
            }
            set {
                this.encryptDecryptViewField = value;
            }
        }
    }
    
    [Serializable]
    public partial class IMAView {
        
        private string networkLayoutStringField;
        
        private string networkBackgroundImagePathField;
        
        private byte[] networkBackgroundColorField;
        
        private bool useNetworkBackgroundColorField;
        
        [XmlAttributeAttribute()]
        public string NetworkLayoutString {
            get {
                return this.networkLayoutStringField;
            }
            set {
                this.networkLayoutStringField = value;
            }
        }
        
        [XmlAttributeAttribute()]
        public string NetworkBackgroundImagePath {
            get {
                return this.networkBackgroundImagePathField;
            }
            set {
                this.networkBackgroundImagePathField = value;
            }
        }
        
        [XmlAttributeAttribute(DataType="hexBinary")]
        public byte[] NetworkBackgroundColor {
            get {
                return this.networkBackgroundColorField;
            }
            set {
                this.networkBackgroundColorField = value;
            }
        }
        
        [XmlAttributeAttribute()]
        public bool UseNetworkBackgroundColor {
            get {
                return this.useNetworkBackgroundColorField;
            }
            set {
                this.useNetworkBackgroundColorField = value;
            }
        }
    }
    
    [Serializable]
    public partial class TestS0Settings {
        
        private byte[] nonceInNetworkKeySetField;
        
        private byte[] mACInNetworkKeySetField;
        
        private byte[] valueInNetworkKeySetField;
        
        private byte valueInSchemeGetField;
        
        private bool valueInSchemeGetFieldSpecified;
        
        private byte valueInSchemeInheritField;
        
        private bool valueInSchemeInheritFieldSpecified;
        
        private byte delaySchemeGetField;
        
        private bool delaySchemeGetFieldSpecified;
        
        private byte delayNonceGetField;
        
        private bool delayNonceGetFieldSpecified;
        
        private byte delayNetworkKeySetField;
        
        private bool delayNetworkKeySetFieldSpecified;
        
        private byte delayNonceReportField;
        
        private bool delayNonceReportFieldSpecified;
        
        private byte delaySchemeInheritField;
        
        private bool delaySchemeInheritFieldSpecified;
        
        private byte[] nonceInNetworkKeyVerifyField;
        
        private byte[] mACInNetworkKeyVerifyField;
        
        private byte[] valueInNetworkKeyVerifyField;
        
        private byte valueInSchemeReportField;
        
        private bool valueInSchemeReportFieldSpecified;
        
        private byte delaySchemeReportField;
        
        private bool delaySchemeReportFieldSpecified;
        
        private byte delayNonceReportINField;
        
        private bool delayNonceReportINFieldSpecified;
        
        private byte delayNonceGetINField;
        
        private bool delayNonceGetINFieldSpecified;
        
        private byte delayNetworkKeyVerifyField;
        
        private bool delayNetworkKeyVerifyFieldSpecified;
        
        private byte delaySchemeInheritReportField;
        
        private bool delaySchemeInheritReportFieldSpecified;
        
        private bool reuseReceiverNonceInSecondFragmentField;
        
        public TestS0Settings() {
            this.reuseReceiverNonceInSecondFragmentField = false;
        }
        
        [XmlAttributeAttribute(DataType="hexBinary")]
        public byte[] NonceInNetworkKeySet {
            get {
                return this.nonceInNetworkKeySetField;
            }
            set {
                this.nonceInNetworkKeySetField = value;
            }
        }
        
        [XmlAttributeAttribute(DataType="hexBinary")]
        public byte[] MACInNetworkKeySet {
            get {
                return this.mACInNetworkKeySetField;
            }
            set {
                this.mACInNetworkKeySetField = value;
            }
        }
        
        [XmlAttributeAttribute(DataType="hexBinary")]
        public byte[] ValueInNetworkKeySet {
            get {
                return this.valueInNetworkKeySetField;
            }
            set {
                this.valueInNetworkKeySetField = value;
            }
        }
        
        [XmlAttributeAttribute()]
        public byte ValueInSchemeGet {
            get {
                return this.valueInSchemeGetField;
            }
            set {
                this.valueInSchemeGetField = value;
            }
        }
        
        [XmlIgnoreAttribute()]
        public bool ValueInSchemeGetSpecified {
            get {
                return this.valueInSchemeGetFieldSpecified;
            }
            set {
                this.valueInSchemeGetFieldSpecified = value;
            }
        }
        
        [XmlAttributeAttribute()]
        public byte ValueInSchemeInherit {
            get {
                return this.valueInSchemeInheritField;
            }
            set {
                this.valueInSchemeInheritField = value;
            }
        }
        
        [XmlIgnoreAttribute()]
        public bool ValueInSchemeInheritSpecified {
            get {
                return this.valueInSchemeInheritFieldSpecified;
            }
            set {
                this.valueInSchemeInheritFieldSpecified = value;
            }
        }
        
        [XmlAttributeAttribute()]
        public byte DelaySchemeGet {
            get {
                return this.delaySchemeGetField;
            }
            set {
                this.delaySchemeGetField = value;
            }
        }
        
        [XmlIgnoreAttribute()]
        public bool DelaySchemeGetSpecified {
            get {
                return this.delaySchemeGetFieldSpecified;
            }
            set {
                this.delaySchemeGetFieldSpecified = value;
            }
        }
        
        [XmlAttributeAttribute()]
        public byte DelayNonceGet {
            get {
                return this.delayNonceGetField;
            }
            set {
                this.delayNonceGetField = value;
            }
        }
        
        [XmlIgnoreAttribute()]
        public bool DelayNonceGetSpecified {
            get {
                return this.delayNonceGetFieldSpecified;
            }
            set {
                this.delayNonceGetFieldSpecified = value;
            }
        }
        
        [XmlAttributeAttribute()]
        public byte DelayNetworkKeySet {
            get {
                return this.delayNetworkKeySetField;
            }
            set {
                this.delayNetworkKeySetField = value;
            }
        }
        
        [XmlIgnoreAttribute()]
        public bool DelayNetworkKeySetSpecified {
            get {
                return this.delayNetworkKeySetFieldSpecified;
            }
            set {
                this.delayNetworkKeySetFieldSpecified = value;
            }
        }
        
        [XmlAttributeAttribute()]
        public byte DelayNonceReport {
            get {
                return this.delayNonceReportField;
            }
            set {
                this.delayNonceReportField = value;
            }
        }
        
        [XmlIgnoreAttribute()]
        public bool DelayNonceReportSpecified {
            get {
                return this.delayNonceReportFieldSpecified;
            }
            set {
                this.delayNonceReportFieldSpecified = value;
            }
        }
        
        [XmlAttributeAttribute()]
        public byte DelaySchemeInherit {
            get {
                return this.delaySchemeInheritField;
            }
            set {
                this.delaySchemeInheritField = value;
            }
        }
        
        [XmlIgnoreAttribute()]
        public bool DelaySchemeInheritSpecified {
            get {
                return this.delaySchemeInheritFieldSpecified;
            }
            set {
                this.delaySchemeInheritFieldSpecified = value;
            }
        }
        
        [XmlAttributeAttribute(DataType="hexBinary")]
        public byte[] NonceInNetworkKeyVerify {
            get {
                return this.nonceInNetworkKeyVerifyField;
            }
            set {
                this.nonceInNetworkKeyVerifyField = value;
            }
        }
        
        [XmlAttributeAttribute(DataType="hexBinary")]
        public byte[] MACInNetworkKeyVerify {
            get {
                return this.mACInNetworkKeyVerifyField;
            }
            set {
                this.mACInNetworkKeyVerifyField = value;
            }
        }
        
        [XmlAttributeAttribute(DataType="hexBinary")]
        public byte[] ValueInNetworkKeyVerify {
            get {
                return this.valueInNetworkKeyVerifyField;
            }
            set {
                this.valueInNetworkKeyVerifyField = value;
            }
        }
        
        [XmlAttributeAttribute()]
        public byte ValueInSchemeReport {
            get {
                return this.valueInSchemeReportField;
            }
            set {
                this.valueInSchemeReportField = value;
            }
        }
        
        [XmlIgnoreAttribute()]
        public bool ValueInSchemeReportSpecified {
            get {
                return this.valueInSchemeReportFieldSpecified;
            }
            set {
                this.valueInSchemeReportFieldSpecified = value;
            }
        }
        
        [XmlAttributeAttribute()]
        public byte DelaySchemeReport {
            get {
                return this.delaySchemeReportField;
            }
            set {
                this.delaySchemeReportField = value;
            }
        }
        
        [XmlIgnoreAttribute()]
        public bool DelaySchemeReportSpecified {
            get {
                return this.delaySchemeReportFieldSpecified;
            }
            set {
                this.delaySchemeReportFieldSpecified = value;
            }
        }
        
        [XmlAttributeAttribute()]
        public byte DelayNonceReportIN {
            get {
                return this.delayNonceReportINField;
            }
            set {
                this.delayNonceReportINField = value;
            }
        }
        
        [XmlIgnoreAttribute()]
        public bool DelayNonceReportINSpecified {
            get {
                return this.delayNonceReportINFieldSpecified;
            }
            set {
                this.delayNonceReportINFieldSpecified = value;
            }
        }
        
        [XmlAttributeAttribute()]
        public byte DelayNonceGetIN {
            get {
                return this.delayNonceGetINField;
            }
            set {
                this.delayNonceGetINField = value;
            }
        }
        
        [XmlIgnoreAttribute()]
        public bool DelayNonceGetINSpecified {
            get {
                return this.delayNonceGetINFieldSpecified;
            }
            set {
                this.delayNonceGetINFieldSpecified = value;
            }
        }
        
        [XmlAttributeAttribute()]
        public byte DelayNetworkKeyVerify {
            get {
                return this.delayNetworkKeyVerifyField;
            }
            set {
                this.delayNetworkKeyVerifyField = value;
            }
        }
        
        [XmlIgnoreAttribute()]
        public bool DelayNetworkKeyVerifySpecified {
            get {
                return this.delayNetworkKeyVerifyFieldSpecified;
            }
            set {
                this.delayNetworkKeyVerifyFieldSpecified = value;
            }
        }
        
        [XmlAttributeAttribute()]
        public byte DelaySchemeInheritReport {
            get {
                return this.delaySchemeInheritReportField;
            }
            set {
                this.delaySchemeInheritReportField = value;
            }
        }
        
        [XmlIgnoreAttribute()]
        public bool DelaySchemeInheritReportSpecified {
            get {
                return this.delaySchemeInheritReportFieldSpecified;
            }
            set {
                this.delaySchemeInheritReportFieldSpecified = value;
            }
        }
        
        [XmlAttributeAttribute()]
        [DefaultValueAttribute(false)]
        public bool ReuseReceiverNonceInSecondFragment {
            get {
                return this.reuseReceiverNonceInSecondFragmentField;
            }
            set {
                this.reuseReceiverNonceInSecondFragmentField = value;
            }
        }
    }
    
    [Serializable]
    public partial class TestS2Settings {
        
        private ObservableCollection<TestParametersS2Settings> parametersField;
        
        private ObservableCollection<TestFrameS2Settings> framesField;
        
        private ObservableCollection<TestExtensionS2Settings> extensionsField;
        
        private bool isOverrideExistingExtensionsField;
        
        private bool isOverrideExistingExtensionsFieldSpecified;
        
        [XmlArrayItemAttribute("Parameter")]
        public ObservableCollection<TestParametersS2Settings> Parameters {
            get {
                return this.parametersField;
            }
            set {
                this.parametersField = value;
            }
        }
        
        [XmlArrayItemAttribute("Frame")]
        public ObservableCollection<TestFrameS2Settings> Frames {
            get {
                return this.framesField;
            }
            set {
                this.framesField = value;
            }
        }
        
        [XmlArrayItemAttribute("Extension")]
        public ObservableCollection<TestExtensionS2Settings> Extensions {
            get {
                return this.extensionsField;
            }
            set {
                this.extensionsField = value;
            }
        }
        
        [XmlAttributeAttribute()]
        public bool IsOverrideExistingExtensions {
            get {
                return this.isOverrideExistingExtensionsField;
            }
            set {
                this.isOverrideExistingExtensionsField = value;
            }
        }
        
        [XmlIgnoreAttribute()]
        public bool IsOverrideExistingExtensionsSpecified {
            get {
                return this.isOverrideExistingExtensionsFieldSpecified;
            }
            set {
                this.isOverrideExistingExtensionsFieldSpecified = value;
            }
        }
    }
    
    [Serializable]
    public partial class EncryptDecryptView {
        
        private bool isTabS0SelectedField;
        
        [XmlAttributeAttribute()]
        public bool IsTabS0Selected {
            get {
                return this.isTabS0SelectedField;
            }
            set {
                this.isTabS0SelectedField = value;
            }
        }
    }
    
    [Serializable]
    public partial class SecurityView {
        
        private bool isTabS0SelectedField;
        
        [XmlAttributeAttribute()]
        public bool IsTabS0Selected {
            get {
                return this.isTabS0SelectedField;
            }
            set {
                this.isTabS0SelectedField = value;
            }
        }
    }
    
    [Serializable]
    [XmlTypeAttribute(AnonymousType=true)]
    [XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class SecuritySettings {
        
        private Collection<NetworkKey> networkKeyField;
        
        private TestS2Settings testS2SettingsField;
        
        private TestS0Settings testS0SettingsField;
        
        private bool isCsaEnabledField;
        
        private bool isCsaEnabledFieldSpecified;
        
        private bool isPausedField;
        
        private bool isPausedFieldSpecified;
        
        private byte[] commandClassesField;
        
        [XmlElementAttribute("NetworkKey")]
        public Collection<NetworkKey> NetworkKey {
            get {
                return this.networkKeyField;
            }
            set {
                this.networkKeyField = value;
            }
        }
        
        public TestS2Settings TestS2Settings {
            get {
                return this.testS2SettingsField;
            }
            set {
                this.testS2SettingsField = value;
            }
        }
        
        public TestS0Settings TestS0Settings {
            get {
                return this.testS0SettingsField;
            }
            set {
                this.testS0SettingsField = value;
            }
        }
        
        [XmlAttributeAttribute()]
        public bool IsCsaEnabled {
            get {
                return this.isCsaEnabledField;
            }
            set {
                this.isCsaEnabledField = value;
            }
        }
        
        [XmlIgnoreAttribute()]
        public bool IsCsaEnabledSpecified {
            get {
                return this.isCsaEnabledFieldSpecified;
            }
            set {
                this.isCsaEnabledFieldSpecified = value;
            }
        }
        
        [XmlAttributeAttribute()]
        public bool IsPaused {
            get {
                return this.isPausedField;
            }
            set {
                this.isPausedField = value;
            }
        }
        
        [XmlIgnoreAttribute()]
        public bool IsPausedSpecified {
            get {
                return this.isPausedFieldSpecified;
            }
            set {
                this.isPausedFieldSpecified = value;
            }
        }
        
        [XmlAttributeAttribute(DataType="hexBinary")]
        public byte[] CommandClasses {
            get {
                return this.commandClassesField;
            }
            set {
                this.commandClassesField = value;
            }
        }
    }
    
    [Serializable]
    [XmlTypeAttribute(AnonymousType=true)]
    [XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class TestSecuritySettings {
        
        private TestS2Settings testS2SettingsField;
        
        private TestS0Settings testS0SettingsField;
        
        private string appVersionField;
        
        public TestS2Settings TestS2Settings {
            get {
                return this.testS2SettingsField;
            }
            set {
                this.testS2SettingsField = value;
            }
        }
        
        public TestS0Settings TestS0Settings {
            get {
                return this.testS0SettingsField;
            }
            set {
                this.testS0SettingsField = value;
            }
        }
        
        [XmlAttributeAttribute()]
        public string AppVersion {
            get {
                return this.appVersionField;
            }
            set {
                this.appVersionField = value;
            }
        }
    }
}
