# YAML -*- mode: yaml; tab-width: 2; indent-tabs-mode: nil; coding: utf-8 -*-
# SPDX-License-Identifier: BSD-3-Clause
# SPDX-FileCopyrightText: 2024 Z-Wave Alliance
# Demo copied from https://docs.github.com/en/actions/quickstart
name: Build and Test Z-Wave PC Controller

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-test-z-wave-tools-core:
    runs-on: windows-latest
    defaults:
      run:
        shell: powershell
    env:
      Solution_Path: z-wave-pc-controller/ZWaveController.sln
      Artifact_Path: ${{ github.workspace }}/artifacts # MSBuild does not support relative paths
      
    steps:
      - name: Checkout z-wave-pc-controller 
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_PAT }}
          path: '/z-wave-pc-controller'

      - name: Checkout z-wave-tools-core
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_PAT }}
          repository: 'Z-Wave-Alliance/z-wave-tools-core'
          path: '/z-wave-tools-core'

      - name: Checkout z-wave-blobs
        uses: actions/checkout@v4
      - name: Checkout z-wave-pc-controller 
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_PAT }}
          path: '/z-wave-pc-controller'

      - name: Checkout z-wave-tools-core
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_PAT }}
          repository: 'Z-Wave-Alliance/z-wave-tools-core'
          path: '/z-wave-tools-core'

      - name: Checkout z-wave-blobs
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_PAT }}
          repository: '-Wave-Alliance/z-wave-blobs'
          path: '/z-wave-tools-core'

      - name: Add MSBuild.exe to Path
        uses: microsoft/setup-msbuild@v1.1

      - name: Restore NuGet Packages for Z-Wave Tools Core Solution
        run: msbuild $env:Solution_Path -restore -verbosity:minimal

      - name: Build Z-Wave PC Controller Solution in Release
        run: |
          msbuild $env:Solution_Path -property:Platform=$env:TargetPlatform -property:Configuration=$env:Configuration -verbosity:minimal
        env:
          Configuration: Release
          TargetPlatform: Any CPU

      - name: Build Z-Wave PC Controller Solution in Debug
        run: |
          msbuild $env:Solution_Path -p:Platform=$env:TargetPlatform -p:Configuration=$env:Configuration -verbosity:minimal
        env:
          Configuration: Debug
          TargetPlatform: Any CPU

      - name: Publish Z-Wave PC Controller Artifacts
        # Release build without debug symbols
        run: msbuild $env:Solution_Path -p:Platform=$env:TargetPlatform -p:Configuration=$env:Configuration -p:OutputPath=$env:Artifact_Path -p:DebugType=None -p:DebugSymbols=false -verbosity:minimal
        env:
          Configuration: Release
          TargetPlatform: Any CPU

      - name: Upload published artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ZWavePCController
          # Windows only tool
          # Explicitly specify the path to the artifacts because the default is the working directory
          path: ${{ env.Artifact_Path }}/*
          retention-days: 5
          if-no-files-found: error
